apiVersion: v1
kind: Service
metadata:
  name: http-probe-test-app
  labels:
    app: http-probe-test-app
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: http-probe-test-app
